-- Flyway migration V1: initial schema for FinTrack (PostgreSQL)
-- Includes normalized, user-scoped budget_months (id UUID PK, user_profile_id + year + month unique)

create table if not exists user_profiles
(
    credit_card_limit_try numeric(38, 2)              not null,
    net_salary_usd        numeric(12, 6)              not null,
    created_at            timestamp(6) with time zone not null,
    id                    uuid                        not null
        primary key,
    email                 varchar(255)                not null
        unique,
    password              varchar(255)                not null,
    username              varchar(255)                not null
        unique
);

create table if not exists budget_months
(
    id              uuid           not null
        primary key,

    user_profile_id uuid           not null
        references user_profiles(id),

    year            integer        not null,
    month           integer        not null,

    income_try      numeric(38, 2) not null,
    expense_try     numeric(38, 2) not null,
    net_savings_try numeric(38, 2) not null,

    label           varchar(255)   not null
);

create table if not exists budget_categories
(
    limit_try       numeric(38, 2) not null,
    spent_try       numeric(38, 2) not null,
    id              uuid           not null
        primary key,

    user_profile_id uuid           not null
        references user_profiles(id),

    budget_month_id uuid           not null
        references budget_months(id),

    category        varchar(255)   not null
);

create table if not exists investment_assets
(
    avg_cost_try      numeric(38, 2) not null,
    change_percent    numeric(38, 2) not null,
    current_price_try numeric(38, 2) not null,
    profit_loss_try   numeric(38, 2) not null,
    quantity          numeric(38, 2) not null,
    id                uuid           not null
        primary key,
    user_profile_id   uuid           not null
        references user_profiles(id),
    name              varchar(255)   not null,
    symbol            varchar(255)   not null,
    type              varchar(255)   not null
        constraint investment_assets_type_check
            check ((type)::text = any
                   ((array ['CURRENCY'::character varying, 'GOLD_SILVER'::character varying, 'FUND'::character varying, 'STOCK'::character varying])::text[]))
);

create table if not exists refresh_tokens
(
    revoked     boolean      not null,
    created_at  timestamp(6) with time zone,
    expires_at  timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    issued_at   timestamp(6),
    replaced_by bigint,
    user_id     uuid         not null,
    ip_address  varchar(255),
    jti         varchar(255),
    token_hash  varchar(255) not null
        unique,
    user_agent  varchar(255)
);

create table if not exists transactions
(
    amount_try       numeric(38, 2) not null,
    date             date           not null,
    is_installment   boolean        not null,
    months           integer,
    total_try        numeric(38, 2),
    id               uuid           not null
        primary key,
    user_profile_id  uuid           not null
        references user_profiles(id),
    category         varchar(255)   not null,
    payment_method   varchar(255)
        constraint transactions_payment_method_check
            check ((payment_method)::text = any
                   ((array ['CARD'::character varying, 'CASH'::character varying, 'TRANSFER'::character varying])::text[])),
    start_month      varchar(255),
    title            varchar(255)   not null,
    transaction_type varchar(255)   not null
        constraint transactions_transaction_type_check
            check ((transaction_type)::text = any
                   ((array ['INCOME'::character varying, 'EXPENSE'::character varying])::text[]))
);

-- refresh_tokens indexes
create index if not exists idx_refresh_user on refresh_tokens (user_id);
create index if not exists idx_refresh_jti  on refresh_tokens (jti);
